### ISSUE TITLE
getResource:java.io.FileNotFoundException: _sans

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#261]
Trying to build Pakka to Android, first issue was fixed in hxcpp https://github.com/HaxeFoundation/hxcpp/issues/300.

```
BUILD SUCCESSFUL
Total time: 34 seconds
4055 KB/s (92625872 bytes in 22.306s)
	pkg: /data/local/tmp/PakkaPets-debug.apk
Success
Starting: Intent { act=android.intent.action.MAIN cmp=proto.games/.MainActivity }
--------- beginning of main
V/HXCPP   ( 6843): Boot ApplicationMain done
D/Finsky  ( 6764): [1] RestoreTracker.stopServiceIfDone: Restore complete with 0 success and 0 failed.
I/haxe plugin( 6843): Got Load Proc a21aa050
I/haxe plugin( 6843): Got Load Proc a21aa050
I/haxe plugin( 6843): Got Load Proc a21aa050
I/haxe plugin( 6843): Got Load Proc a21aa050
--------- beginning of system
W/ActivityManager(  746): getRunningAppProcesses: caller 10035 does not hold REAL_GET_TASKS; limiting output
W/ActivityManager(  746): getRunningAppProcesses: caller 10035 does not hold REAL_GET_TASKS; limiting output
I/CreateMainFrame!( 6843): creating...
I/Adreno-EGL( 6843): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/14/15, ab0075f, Id3510ff6dc
E/VIEW    ( 6843): Using OpenglES 2.0
D/trace   ( 6843): Construct LindenFlurry
D/trace   ( 6843): LindenFlurry created
D/GameActivity( 6843): ====== doResume ======== org.haxe.nme.MainView{274cb8f6 VFE..... ......I. 0,0-0,0}
V/NME     ( 6843): onResume
D/GameActivity( 6843): super resume
I/System.out( 6843): onRESUME!!!!!!!
V/HXCPP   ( 6843): Boot nme..
V/HXCPP   ( 6843): Boot nme done
V/WindowManager(  746): Adding window Window{17361da u0 proto.games/proto.games.MainActivity} at 4 of 11 (before Window{3d295e59 u0 Starting proto.games})
D/BluetoothAdapter(25550): 772055921: getState() :  mService = null. Returning STATE_OFF
D/BluetoothAdapter(25550): 772055921: getState() :  mService = null. Returning STATE_OFF
V/WindowManager(  746): Adding window Window{3c0a3cdf u0 SurfaceView} at 4 of 13 (before Window{17361da u0 proto.games/proto.games.MainActivity})
V/EGL     ( 6843): Choose config (2) false
V/EGL     ( 6843): Matched depth + stencil : 1(0)
I/ActivityManager(  746): Killing 3799:com.google.android.apps.maps/u0a57 (adj 15): empty #17
V/VIEW    ( 6843): onSurfaceCreated
V/VIEW    ( 6843): Thread = 10145
V/VIEW    ( 6843): onSurfaceChanged 1794,1080
V/VIEW    ( 6843): Thread = 10145
D/WifiService(  746): Client connection lost with reason: 4
V/NME     ( 6843): Send on lost
V/WindowManager(  746): Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
V/WindowManager(  746): Layouts looping: loop number 4, mPendingLayoutChanges = 0x0
V/WindowManager(  746): Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
V/WindowManager(  746): Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
V/WindowManager(  746): Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
V/WindowManager(  746): Layouts looping: loop number 5, mPendingLayoutChanges = 0x0
V/WindowManager(  746): Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
V/WindowManager(  746): Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
E/WindowManager(  746): Performed 6 layouts in a row. Skipping
W/IInputConnectionWrapper( 1237): showStatusIcon on inactive InputConnection
I/Keyboard.Facilitator( 1084): onFinishInput()
I/ActivityManager(  746): Displayed proto.games/.MainActivity: +631ms (total +1m5s371ms)
E/ActivityThread( 1237): Performing stop of activity that is not resumed: {com.google.android.googlequicksearchbox/com.google.android.launcher.GEL}
E/ActivityThread( 1237): java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.google.android.googlequicksearchbox/com.google.android.launcher.GEL}
E/ActivityThread( 1237): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3344)
E/ActivityThread( 1237): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
E/ActivityThread( 1237): 	at android.app.ActivityThread.access$1100(ActivityThread.java:151)
E/ActivityThread( 1237): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
E/ActivityThread( 1237): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread( 1237): 	at android.os.Looper.loop(Looper.java:135)
E/ActivityThread( 1237): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/ActivityThread( 1237): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 1237): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityThread( 1237): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/ActivityThread( 1237): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/GameActivity( 6843): getResource:java.io.FileNotFoundException: _sans
I/WindowManager(  746): Screen frozen for +714ms due to Window{3ec9257 u0 NavigationBar}
--------- beginning of crash
F/libc    ( 6843): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 6888 (GLThread 10145)
W/ActivityManager(  746): getRunningAppProcesses: caller 10035 does not hold REAL_GET_TASKS; limiting output
I/DEBUG   (  186): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

**Comment by thomasuster** [comment]
I rebuilt nme with -debug, that didn't seem to show the stacktrace. I'll try a full rebuild.

**Comment by hughsando** [comment]
I wonder if it is from "getResource:java.io.FileNotFoundException: _sans", which is then causing a null-pointer error later.
There were also an other thread fix recently that might fix a deadlock. https://github.com/HaxeFoundation/hxcpp/commit/c81ac4c85b55434be60dad285dc66a8d823ee470

**Comment by thomasuster** [comment]
I built it with the latest hxcpp including the commit you mentioned. Both hxcpp and nme built with -debug.

The game no longer crashes but instead just hangs at the loading screen.

```
D/GameActivity(20902): ==== onCreate ===== proto.games.MainActivity@433ec07
V/GameActivity(20902): Loading nme...
V/GameActivity(20902): Loading std...
V/GameActivity(20902): Loading zlib...
V/GameActivity(20902): Loading regexp...
D/GameActivity(20902): ====== doResume ======== org.haxe.nme.MainView{274cb8f6 VFE..... ......I. 0,0-0,0}
D/GameActivity(20902): super resume
E/GameActivity(20902): getResource:java.io.FileNotFoundException: _sans
```
I don't know what _sans is from. Nor do I know why it didn't crash this time. Other ideas?

**Comment by hughsando** [comment]
This looks suspiciously like the gc threaded code deadlocking.
Is it only when you are running the IAP code?  Because maybe the threads
are slightly wrong there.
Otherwise, I should be able to reproduce it here - I'll give it a go.

**Comment by thomasuster** [comment]
I don't think it has anything to do with IAP. I just misread "IApp" as IAP from "IAppEventHandler_delegate_".

```
cd pakkaPets
git checkout town
cd bin
sh copyItems.bat
sh texturePack.bat
sh androidDebug.bat
```

**Comment by thomasuster** [comment]
Did some narrowing it down. If you do this.

```
cd pakkaPets
git checkout town-issue-261
sh androidDebug.bat
```

Then close hung game on phone and do.

```
adb logcat -s trace
```

You should see.

```
I/trace   ( 7895): SpreadSystem.hx:76: ConfigureContextVO
I/trace   ( 7895): ConfigureContextCommand.hx:10: pakka.doors.tree.TreeConfig
I/trace   ( 7895): GameContext.hx:122: 0
I/trace   ( 7895): GameContext.hx:125: 1
I/trace   ( 7895): GameContext.hx:127: 2
I/trace   ( 7895): GameContext.hx:129: 3
I/trace   ( 7895): GameContext.hx:132: 4 pakka.doors.tree.TreeConfig
I/trace   ( 7895): TreeConfig.hx:45: 0
I/trace   ( 7895): TreeConfig.hx:48: 1
I/trace   ( 7895): TreeConfig.hx:65: 2
I/trace   ( 7895): TreeConfig.hx:68: 3
```
Which has nothing to do with anything really. So this really feels like hxcpp dead lock.

**Comment by thomasuster** [comment]
I built it today with the latest.

The...
```
E/GameActivity( 6843): getResource:java.io.FileNotFoundException: _sans
```
Is a crash, I think because of changes in /Users/thomasuster/nme/project/src/common/FreeType.cpp maybe?

I use the nme.display. FPS for debug android builds, when I comment this out the problem doesn't occur anymore. Inside FPS it references _sans. I never included _sans in my *.nmml before, maybe now the intent is I do?

Any ideas @codeservice?

**Comment by hughsando** [comment]
Ok - that should be easy enough to test.  I think the logic should be that
it looks for the "_sans" font (in case the developer redefines it), does
not find it and then uses a substitute font from the android area.  But
looks like it is crashing when it does not find it.

**Comment by thomasuster** [comment]
Okay, I did some more digging. The exact same code with NME compiled using -debug doesn't crash and displays the FPS meter as expected. It also prints the same FileNotFoundException exception. This along with my digging around in git history makes me believe the FileNotFoundException has existed for a long time in the current working version, and is therefore a red hearing.

//Working output with some custom traces.
```
I/GetFontFile(16299): Loading font _sans.
I/GetFontFile(16299): 0
I/System.out(16299): _sans
E/GameActivity(16299): getResource:java.io.FileNotFoundException: _sans
I/GetFontFile(16299): 1
I/GetFontFile(16299): Found font in /system/fonts/DroidSans.ttf
```

So the problem is either ```if (android & debug)``` or it's an hxcpp issue?
