### ISSUE TITLE
Android - crash when clearing text and switching textfields

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#325]
To repeat the crash you need to compile to android.  Enter text in field 1 and in field 2 and hit the circle 2 or more times.  The 13 in the error below is how many characters I had entered into to field 1 before clicking the circle.  I believe what is happening is that when the focus is forced back into text1 it assumes there are 13 characters and it is trying to set the focus at the end of those 13 characters  even though the text was removed on the first circle click.

AndroidRuntime: java.lang.IndexOutOfBoundsException: setSpan (13 ... 13) ends beyond length 0
AndroidRuntime:     at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)

```
package;

import flash.events.MouseEvent;
import nme.display.Sprite;
import nme.text.TextField;
import nme.text.TextFieldType;
import nme.Lib;
class Main extends Sprite {
    var text1:TextField;
    var text2:TextField;
    public function new() {
        super();
        this.scaleX = this.scaleY = 5;
        text1 = new TextField();
        text1.type = TextFieldType.INPUT;
        text1.border = true;
        text2 = new TextField();
        text2.type = TextFieldType.INPUT;
        this.addChild(text1);
        this.addChild(text2);
        text2.y = text1.height;
        text2.border = true;

        var square:Sprite = new Sprite();
        square.graphics.beginFill(0, 1);
        square.graphics.drawCircle(150, 50, 10);
        square.graphics.endFill();
        square.addEventListener(MouseEvent.CLICK, doIt);
        this.addChild(square);
    }
    var cnt:Int = 0;
    function doIt(e){
        if (cnt == 0){
            text1.text = "";
            stage.focus = text2;            
            cnt = 1;
        }else{
            stage.focus = text1;
            text2.text = "";
            cnt = 0;
        }
    }

}
```

**Comment by thomasuster** [comment]
Confirmed on latest NME
```
09-23 13:35:13.252 32574 32574 E AndroidRuntime: FATAL EXCEPTION: main
09-23 13:35:13.252 32574 32574 E AndroidRuntime: Process: io.nme.samples.nyancat, PID: 32574
09-23 13:35:13.252 32574 32574 E AndroidRuntime: java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 0
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:76)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:87)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:98)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at org.haxe.nme.GameActivity$7.run(GameActivity.java:1132)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-23 13:35:13.252 32574 32574 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-23 13:35:13.253   778   950 W ActivityManager:   Force finishing activity io.nme.samples.nyancat/.MainActivity
```

**Comment by thomasuster** [comment]
PR for fix -> https://github.com/haxenme/nme/pull/537
