### ISSUE TITLE
Android UnsatisfiedLinkError error after updating NME

### ISSUE THREAD

**Issue by jskuse** [haxenme/nme#429]
I've been updating our projects to use the GIT version of NME (moving from a fork dating mostly back to mid 2016) as well as Haxe 3.4 and the most recent haxelib version of HXCPP. Of course, this means that this is perhaps more of a HXCPP issue than an NME one, apologies if this is the case. 

After a few teething problems with the native code bits of our project we've got it building for Android again, but when ran on an old test device (which previously ran the game just fine) it crashes at startup with the following log.
 
```
W/dalvikvm( 5875): threadid=1: thread exiting with uncaught exception (group=0x40af9228)
E/AndroidRuntime( 5875): FATAL EXCEPTION: main
E/AndroidRuntime( 5875): java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1285]:   105 cannot locate 'stpcpy'...
E/AndroidRuntime( 5875): 
E/AndroidRuntime( 5875): 	at java.lang.Runtime.loadLibrary(Runtime.java:370)
E/AndroidRuntime( 5875): 	at java.lang.System.loadLibrary(System.java:539)
E/AndroidRuntime( 5875): 	at org.haxe.HXCPP.run(HXCPP.java:12)
E/AndroidRuntime( 5875): 	at org.haxe.nme.GameActivity.onCreate(GameActivity.java:176)
```

Reading https://github.com/HaxeFoundation/hxcpp/issues/478, it seems that compatibility with the version of Android on the device is an issue and @hughsando makes specific mention of explicitly setting the platform. Frankly, I have barely any understanding Android as a platform and SDK/NDK versions, API levels etc. puzzle me greatly. 

Verbose output tells us:
```
Using newest Android NDK platform: 24
```

Our project does define the following, but I guess this isn't particularly relevant to what it actually *builds* with:
```
<android minApiLevel="9" targetApiLevel="9" />	
```

It's been a long while since I've attempted an Android build but I don't *think* I've consciously installed any new SDK's since I previously successfully built it, but I could be wrong. 

I did naively attempt to build the game with ```-DPLATFORM=android-19``` which resulted in an errors while linking, including the aforementioned stpcpy:
```
Link: libApplicationMain-v7.so
obj/android-v7/7810a445_timing.obj:timing.c:function sighandler: error: undefined reference to 'signal'
obj/android-v7/7810a445_timing.obj:timing.c:function mbedtls_set_alarm: error: undefined reference to 'signal'
obj/android-v7/7810a445_rsa.obj:rsa.c:function myrand: error: undefined reference to 'rand'
obj/android-v7/29c6540c_gzio.obj:gzio.c:function gzerror: error: undefined reference to 'stpcpy'
```

I'm at a bit of a dead end here, so any hints as to what I should be looking at would be greatly appreciated!

**Comment by hughsando** [comment]
Google keep on moving stuff from inline-header to library implementation.
This means older devices (not that older) do not have the functions in their libraries and you get this error.
I patch them in this file:
https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/AndroidCompat.cpp
so I need to fix it in hxcpp.

**Comment by hughsando** [comment]
It looks like nme should be setting the "PLATFORM" variable, which should really be called "ANDROID_NDK_PLATFORM", explicitly in the Build.xml (nme-dev) and ToolkitBuild.xml (-toolkit) files.
```
   <set name="PLATFORM" value="android-9" if="android" />
   <set name="PLATFORM" value="android-14" if="HXCPP_X86" />
   <set name="PLATFORM" value="android-21" if="HXCPP_ARM64" />
```
This is different to the android "minApiLevel" and "targetApiLevel", which are to do with java, rather than native compilation.

Since you are getting "Using newest Android NDK platform: 24" it means something has gone wrong.

So maybe 'android' is not set.  Are you building with something like "nme android ..." or some other command line?

**Comment by jskuse** [comment]
Thanks Hugh - yeah, I'm building using ```nme test android``` / ```nme build android``` as per usual. 

I can see what you're saying, I'm still pretty lost but at least now I can trace values through the toolchain to *try* and see where things are getting confused. I'm going to have a trawl through AndroidPlatform.hx and see if I can understand how everything fits together a little better.

 In case it sheds any light, the full output around the NDK platform stuff is:
```
Using Android NDK root: /opt/android-ndk
Deduced NDK version 12 from "/opt/android-ndk"/source.properties
Detected Android NDK r12
Detected Android toolchain: arm-linux-androideabi-4.9
Detected Android host: darwin-x86_64
Using newest Android NDK platform: 24
```

**Comment by jskuse** [comment]
Ah! Since you mentioned a difference between toolkit and non-toolkit builds, I just tried a toolkit build (I'd been adopting a change-one-thing-at-a-time approach) and it successfully uses android-9 to build and the game starts up successfully.

So it looks like the issue is specific to the nme-dev build. I seem to remember your plan was to default to toolkit sooner or later anyway wasn't it?

**Comment by jskuse** [comment]
On the off chance that it's any use to you, I also ran a diff on both the ```Build.xml```, ```build.hxml``` and arguments passed into HXCPP for the two builds. 

The only noteworthy differences (beyond the presence of ```toolkit``` being defined and ```--times``` being added for the toolkit build) are in the Build.xml, with the following sections added for the toolkit build. 

```
<file name="src/nme/StaticNme.cpp" >
  <depend name="include/nme/StaticNme.h"/>
</file>
```
```
<depend name="include/nme/StaticNme.h"/>
```
```
<set name='NME_STATIC_LINK' value='1' />
<import name='/usr/local/lib/haxe/lib/nme/git/project/ToolkitBuild.xml'/>
<target id='haxe'>
  <merge id='nme-target'/>
</target>;
```

There isn't anything noteworthy extra in the non-toolkit build that isn't *also* in the toolkit build. 

This is all black magic to me, but given what you were saying above about the ```PLATFORM``` variable being set in ```ToolkitBuild.xml``` and ```Build.xml```, and given that ```ToolkitBuild.xml``` gets imported for the toolkit build, I can't see anything setting ```PLATFORM``` for the non-toolkit build.

**Comment by hughsando** [comment]
Ahhhh, yes.
There are actually 3 build.xml file.
project/ToolkitBuild.xml - building apps with -toolkit
project/Build.xml  - for prebuilding the ndll and prebuilding the nme
static-lib with nme-dev
lib/NmeLink.ml - for static linking with pre-built static-lib with nme-dev
builds

Compiling with HXCPP_VERBOSE should show which files are being included

The last one does not set the platform, so although nme is building an
linking ok, the mbedtls  for ssl lib in hxcpp is not seeing the PLATFORM
define, since it is not in lib/NmeLink.xml.  So this is really a hxcpp
issue - I have added a wrapper, so I hope this is fixed there.

Maybe I should use similar logic to default the platform in hxcpp, so this
 would not be needed in nme.

**Comment by jskuse** [comment]
Glad that's starting to make sense. 

Do you think NME will be moving over to defaulting to toolkit and depreciating the nme-dev approach in the nearish future? It feels like maintaining both might prove a pain and the the toolkit model is certainly a lot cleaner (or at least from my very limited perspective it is). Although that said, amusingly I'm having some issues with toolkit builds under iOS, but that's for another day / issue! 

Thanks again for the help, it's really appreciated.

**Comment by thomasuster** [comment]
Hey @jskuse, is this issue resolved?
