### ISSUE TITLE
JS Prime - out of memory

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#474]
Private project just testing "nme test application.xml html5".  Let me know if this makes sense or if you need a repeatable project
`Running...
index.html:96 
index.html:54 TODO unrealize object Bytes
index.html:54 Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
index.html:93 Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
printErr @ index.html:93
ApplicationMain.js:5211 Exception: abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (http://localhost:6931/Nme.js:1:17947)
    at stackTrace (http://localhost:6931/Nme.js:1:18118)
    at abort (http://localhost:6931/Nme.js:36:11265)
    at abortOnCannotGrowMemory (http://localhost:6931/Nme.js:1:19000)
    at enlargeMemory (http://localhost:6931/Nme.js:1:19445)
    at PIa (http://localhost:6931/Nme.js:29:72259)
    at gGa (http://localhost:6931/Nme.js:29:19154)
    at Array.el (http://localhost:6931/Nme.js:6:70236)
    at Object.YIa [as dynCall_vi] (http://localhost:6931/Nme.js:29:73196)
    at invoke_vi (http://localhost:6931/Nme.js:1:268837)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

ApplicationMain.js:5212 

===Terminating===
.
index.html:93 exception thrown: Error: Unhandled exception:abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (http://localhost:6931/Nme.js:1:17947)
    at stackTrace (http://localhost:6931/Nme.js:1:18118)
    at abort (http://localhost:6931/Nme.js:36:11265)
    at abortOnCannotGrowMemory (http://localhost:6931/Nme.js:1:19000)
    at enlargeMemory (http://localhost:6931/Nme.js:1:19445)
    at PIa (http://localhost:6931/Nme.js:29:72259)
    at gGa (http://localhost:6931/Nme.js:29:19154)
    at Array.el (http://localhost:6931/Nme.js:6:70236)
    at Object.YIa [as dynCall_vi] (http://localhost:6931/Nme.js:29:73196)
    at invoke_vi (http://localhost:6931/Nme.js:1:268837)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.,Error: Unhandled exception:abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (http://localhost:6931/Nme.js:1:17947)
    at stackTrace (http://localhost:6931/Nme.js:1:18118)
    at abort (http://localhost:6931/Nme.js:36:11265)
    at abortOnCannotGrowMemory (http://localhost:6931/Nme.js:1:19000)
    at enlargeMemory (http://localhost:6931/Nme.js:1:19445)
    at PIa (http://localhost:6931/Nme.js:29:72259)
    at gGa (http://localhost:6931/Nme.js:29:19154)
    at Array.el (http://localhost:6931/Nme.js:6:70236)
    at Object.YIa [as dynCall_vi] (http://localhost:6931/Nme.js:29:73196)
    at invoke_vi (http://localhost:6931/Nme.js:1:268837)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
    at nme_display_Stage.onUnhandledException (http://localhost:6931/ApplicationMain.js:5213:10)
    at nme_app_Window.nmeProcessWindowEvent (http://localhost:6931/ApplicationMain.js:4460:25)
    at f (http://localhost:6931/ApplicationMain.js:6860:242)
    at __emval_call (http://localhost:6931/Nme.js:1:186364)
    at Array.fLa (http://localhost:6931/Nme.js:29:80546)
    at Object.eJa [as dynCall_iiiii] (http://localhost:6931/Nme.js:29:73883)
    at invoke_iiiii (http://localhost:6931/Nme.js:1:270238)
    at Array.qP (http://localhost:6931/Nme.js:12:224246)
    at PA (http://localhost:6931/Nme.js:5:48391)
    at Array.Bj (http://localhost:6931/Nme.js:6:43119)
printErr @ index.html:93
Nme.js:1 Uncaught js__$Boot_HaxeError
`

**Comment by hughsando** [comment]
Looks like I had a small logic error building nme.js.
The "TODO unrealize object Bytes" might need some attention too.

**Comment by hoseyjoe** [comment]
Once I commented out #475 I was able to compile nme.js....Do I have to do that for nightlies?  Anyways...I saw the application run for 6 seconds before crashing again. IDK

**Comment by CQDean** [comment]
I changed HXCPP_LINK_TOTAL_MEMORY to 1gb in ToolkitBuild.xml, rebuilt, and re-ran, watching memory usage.  It just filled up right to that 1gb mark and then crashed.  Something is burning through memory very quickly.

**Comment by hughsando** [comment]
The JS Prime code needs special attention to deal with references because js inside a browser does not have finalizers.
Looks like I have missed something.  As you see, increasing the memory only offers a brief reprieve.
Do you have some sample code?  Suspect operations would include creating DisplayObjects in a loop - perhaps bitmaps or sounds.  Possibly ByteArray too.
If you can comment out parts of the code to fix the problem, that should point at what is wrong.
Also, WeakReferences will not work.
