### ISSUE TITLE
[android] java.lang.UnsatisfiedLinkError?

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#601]
Any ideas on this one?

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/proto.games-1/base.apk"],nativeLibraryDirectories=[/data/app/proto.games-1/lib/x86, /data/app/proto.games-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libApplicationMain.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
       at java.lang.System.loadLibrary(System.java:1582)
       at org.haxe.HXCPP.run(HXCPP.java:12)
       at org.haxe.nme.GameActivity.onCreate(GameActivity.java:183)
       at android.app.Activity.performCreate(Activity.java:6682)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by hughsando** [comment]
Is this running x86? simulator?  Maybe this dll needs compiling.

**Comment by thomasuster** [comment]
@hughsando No, this is in production on devices.

<img width="444" alt="Screen Shot 2019-04-21 at 5 28 36 PM" src="https://user-images.githubusercontent.com/220965/56477485-eeef3880-645a-11e9-9fbb-e3bb62d126bf.png">

**Comment by thomasuster** [comment]
I also tried a build with `neko build.n mac ios android`, same issue.
