### ISSUE TITLE
[android] Null mView

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#611]
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'org.haxe.nme.MainView org.haxe.nme.GameActivity.mView' on a null object reference
       at org.haxe.nme.GameActivity$6.run(GameActivity.java:1253)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6320)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by thomasuster** [comment]
```
public static void popupKeyboard(final  int inMode, final  String inContent, final int inType)
   {
      if(activity == null) {
        Log.i("VIEW","popupKeyboard occured after destruction, ignoring...");
        return;
      }
        
      activity.mHandler.post(new Runnable() {
         @Override public void run()
         {
         InputMethodManager mgr = (InputMethodManager)mContext.getSystemService(Context.INPUT_METHOD_SERVICE);
         mgr.hideSoftInputFromWindow(activity.mView.getWindowToken(), 0); //<-- 1253
         
```
